### ISSUE TITLE
Automatische Fehlermeldung per Mail

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#34]
Sollte bei der Kassa etwas passieren, könnte eine Fehlermeldung automatisch per Mail verschickt werden. Zumindest im ersten Jahr. an einen von uns beiden.

**Comment by cssack** [comment]
das geht dann aber auch nur wenn wir einen smtp server haben

**Comment by mssack** [comment]
glaub ich bekommen wir

**Comment by cssack** [comment]
ich richte das aufjeden fall ein. Es muss halt dann eine gültige Konfiguration dort an der Kasse sein

**Comment by cssack** [comment]
passt

**Comment by mssack** [comment]
ich muss ja auch bauen, dass er geburtstagsmails verschickt. also eigentlich bin ich mir sicher dass smtp gibt

**Comment by cssack** [comment]
passt betrachte es als erledigt. Ich lasse eine mail an uns beide schicken mit der entsprechenden Fehlermeldung
