### ISSUE TITLE
einstellungen merken bei beleg abschluss

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#36]
StartupModes.BelegDataApprove
Man kann das drucken und mail versenden auf und zuklappen. Bitte hier auch merken obs auf oder zugeklappt geschlossen wurde.

**Comment by cssack** [comment]
hier benutze ich anundfürsich eine andere logik
Wenn gedruckt wird ist es aufgeklappt
wenn es nicht gedruckt wird zu.

Das selbe gilt für die mails

**Comment by mssack** [comment]
is auch ok

**Comment by cssack** [comment]
weil weißt eh sonst schließt er das du hast das flag drucken auf true, und er sieht dann nicht das gedruckt wird

**Comment by cssack** [comment]
ich schließe das feature

**Comment by mssack** [comment]
passt
