### ISSUE TITLE
NceKommentar

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#37]
Es wird der Kommentar nicht übernommen den man mit NceKommentar übergibt.

**Comment by cssack** [comment]
stimmt ist auch der falsche parameter 
stattdessen bitte 
/NceComment benutzen

Wiki ist schon ausgebessert ich schließe den bug in 5 min

**Comment by cssack** [comment]
sollen wir vielleicht eventuell noch ein feld einfügen wie zahlungsreference

**Comment by mssack** [comment]
weis nicht, eigentlich wird in meinem programm eh nix nachgeschaut, ich möcht kein buchhaltungsprogramm baun

**Comment by cssack** [comment]
passt, dar fich fragen wofür der kommentar?

**Comment by mssack** [comment]
für die zalungsreferenz

**Comment by mssack** [comment]
aber vielleicht nehm ich das eh wieder raus

**Comment by cssack** [comment]
haha xD ich werde in jedem fall so ein feld einführen ich halte das für sinnvoll. Egal ob es dann benutzt wird oder nicht
