### ISSUE TITLE
groesse bon

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#40]
StartupModes.BelegDataApprove:
Bei der Vorschau vom bon, bitte zum Boninhalt runterscrollen, oder noch besser den bon kleiner darstellen, damit man möglichst alles sieht.
![logo](https://cloud.githubusercontent.com/assets/19372091/15286994/51b05432-1b60-11e6-8579-ea89bd0aa995.jpg)

**Comment by cssack** [comment]
Kannst du mir ein screenshot von diesem Problem machen genau weiß ich noch nicht wo das Problem lliegt ;)
