### ISSUE TITLE
beenden knopf

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#42]
Den Beenden Knopf größer oder ein Zurück Knopf, damit man von deinem Fenster wieder zu meinem Kommt: Viewer und Options

**Comment by cssack** [comment]
hmmm ehrlich gesagt will ich das nicht. Das Wiederspricht den Desing principles. User kennen den x Button und sollen diesen auch benutzen.

**Comment by mssack** [comment]
diesen issue kann man schließen, weil der x knopf groß genug ist, weil ich verstanden hab was das skalieren macht.
