### ISSUE TITLE
bon vorschau standard wert

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#43]
Ich habe eine Rechnung erstellt, aber bekomme bei der Vorschau für die Rechnung immer noch folgenden roten Text: "Es wurden keine Rechnungen erstellt. Daher wurde der default gewählt!"
BelegDataApprove

**Comment by cssack** [comment]
kann sein das du weder einen ausdruck noch eine mail mit layout erstellt hast? Ich hab diese Vorschau für die vefschiedensten Layouts die bei mails oder bei ausdrücken eingefügt sind
