### ISSUE TITLE
passwort für Mail Account verdecken

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#53]
Bitte das Passwort beim Mail Client verdecken, zum Beispiel: #####

**Comment by cssack** [comment]
Vielen dank für das gelungene beispiel 😂

**Comment by mssack** [comment]
das war zum veranschaulichen du gluckschaißer

**Comment by cssack** [comment]
Ja dann vielen dank für die veranschaulichung oberst hirn im team
