### ISSUE TITLE
rechtsklick auf icon in Startleiste und beenden beendet die kassa

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#54]
Wenn man unten in der Taskleiste mit der rechten maustaste auf das Icon von der kassa drückt, dann kann man auf beenden gehen und die kassa schließt sich einfach. Bitte noch eine Abfrage oder sonst was sinnvolles einbauen.

**Comment by cssack** [comment]
ei mir geht das nicht. Um welches fenster reden wir hier

**Comment by mssack** [comment]
ah, sorry da hab ich vergessen hinzuzufügen: Wenn das mailen nicht funktioniert oder die Druckabfrage offen ist. Also es reicht eine falsche Mail Adresse einzugeben, dann sagt er er möchte drucken und dann kann man das Fenster schließen
