### ISSUE TITLE
email betreff editierbar

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#80]
eine Möglichkeit im email betreff was anzuhängen.

**Comment by cssack** [comment]
Was meinst du etwas in den Email betreff anhängen?

**Comment by mssack** [comment]
bitte auch über die parameter

**Comment by cssack** [comment]
Hmmm, ich kann dir eigentlich nur die Möglichkeit geben den Betreff komplett zu überschreiben etwas anzuhängen am bereits bestehenden Betreff will ich eigentlich nicht einbauen.

**Comment by mssack** [comment]
is gekuaft
