### ISSUE TITLE
zu wenig platz bei den optionen

### ISSUE THREAD

**Issue by mssack** [cssack/ProjectSchmid#83]
Wenn man ein neues layout machen möchte und man hat einen zu kleinen Bildschirm, dann kann man kaum alles bedienen weil zu wenig platz ist. Vielleicht, dass man die Vorschau wegklappen kann.

**Comment by cssack** [comment]
welche auflösung und welche skalierung in den optionen?

**Comment by mssack** [comment]
Skalierung ganz klein und Auflösung irgendein scheis vom Schmid weil er 2 ganz unterschiedliche bildschime gleichzeitig hat

**Comment by mssack** [comment]
1152x8..
